# Generated by Django 4.2.21 on 2025-06-01 05:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('far_id', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('asset_type', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('useful_life_years', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('note', models.TextField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('Available', 'Available'), ('Allocated', 'Allocated')], default='Available', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('contact_info', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocation_date', models.DateField()),
                ('deallocation_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='assets.asset')),
                ('resource_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='assets.resourceuser')),
            ],
            options={
                'ordering': ['-allocation_date'],
            },
        ),
    ]
