services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: resource_allocator_db
      POSTGRES_USER: allocator_user
      POSTGRES_PASSWORD: securepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  postgres_data:
